#*******************************************************************************
#   Ledger SDK
#   (c) 2017 Ledger
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#*******************************************************************************
#allow for makefile override of the default placement for generated glyph header/c files
ifeq ($(GLYPH_SRC_DIR),)
GLYPH_SRC_DIR = src
endif
ifeq ($(BOLOS_SDK),)
$(error BOLOS_SDK not set)
endif

GLYPH_DESTC := $(GLYPH_SRC_DIR)/glyphs.c
GLYPH_DESTH := $(GLYPH_SRC_DIR)/glyphs.h

ifeq ($(TARGET_NAME),TARGET_FATSTACKS)
# Fatstacks glyphs files and generation script
GLYPH_FILES += $(addprefix $(BOLOS_SDK)/lib_nbgl/glyphs/,$(sort $(notdir $(shell find $(BOLOS_SDK)/lib_nbgl/glyphs/))))
GLYPH_FILES += $(addprefix glyphs/,$(sort $(notdir $(shell find glyphs/))))
ifneq (,$(wildcard $(ICONNAME)))
# Do not try to generate app icon glyph, if image does not exist
GLYPH_FILES += $(ICONNAME)
endif
ICON_SCRIPT = $(BOLOS_SDK)/lib_nbgl/tools/icon2glyph.py
GENERATE_GLYPHS_CMD = python3 $(ICON_SCRIPT) --glyphcfile $(GLYPH_FILES) > $(GLYPH_DESTC)
else
# Nano glyphs files and generation script
GLYPH_FILES += $(foreach gp,$(GLYPH_PATH),$(addprefix $(gp)/,$(sort $(notdir $(shell find $(gp))))))
GLYPH_FILES += $(addprefix glyphs/,$(sort $(notdir $(shell find glyphs/))))
GLYPH_FILES += $(addprefix $(BOLOS_SDK)/lib_ux/glyphs/,$(sort $(notdir $(shell find $(BOLOS_SDK)/lib_ux/glyphs/))))
ICON_SCRIPT = $(BOLOS_SDK)/icon3.py
GENERATE_GLYPHS_CMD = python3 $(ICON_SCRIPT) --factorize --glyphcfile $(GLYPH_FILES) > $(GLYPH_DESTC)
endif

$(GLYPH_DESTH): $(GLYPH_FILES) $(ICON_SCRIPT)
	$(L)echo [GLYPH] Compiling...
	$(L)-mkdir -p $(GLYPH_SRC_DIR)
	$(L)python3 $(ICON_SCRIPT) --glyphcheader $(GLYPH_FILES) > $(GLYPH_DESTH)
	$(L)$(GENERATE_GLYPHS_CMD)

#add dependency for generation
$(GLYPH_DESTC): $(GLYPH_DESTH)
