#*******************************************************************************
#   Ledger SDK
#   (c) 2017 Ledger
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#*******************************************************************************
#allow for makefile override of the default placement for generated glyph header/c files
ifeq ($(GLYPH_SRC_DIR),)
GLYPH_SRC_DIR = src
endif
ifeq ($(BOLOS_SDK),)
$(error BOLOS_SDK not set)
endif

GLYPH_FILES := $(addprefix glyphs/,$(sort $(notdir $(shell find glyphs/))))
GLYPH_DESTC := $(GLYPH_SRC_DIR)/glyphs.c
GLYPH_DESTH := $(GLYPH_SRC_DIR)/glyphs.h
$(GLYPH_DESTH): $(GLYPH_FILES) $(BOLOS_SDK)/icon.py
	$(call log,echo [GLYPH] Compiling...)
	$(call log,-mkdir -p $(GLYPH_SRC_DIR))
	$(call log,-rm $(GLYPH_DESTC) $(GLYPH_DESTH) 2>/dev/null)
	$(call log,touch $(GLYPH_DESTH) $(GLYPH_DESTC))
	$(call log,if [ ! -z "$(GLYPH_FILES)" ] ; then for gif in $(GLYPH_FILES) ; do python $(BOLOS_SDK)/icon.py $$gif glyphcheader ; done > $(GLYPH_DESTH) ; fi)
	$(call log,if [ ! -z "$(GLYPH_FILES)" ] ; then for gif in $(GLYPH_FILES) ; do python $(BOLOS_SDK)/icon.py $$gif glyphcfile ; done > $(GLYPH_DESTC) ; fi)
#add dependency for generation
$(GLYPH_DESTC): $(GLYPH_DESTH)