
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2022 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

// Nano S
#ifdef HAVE_BAGL_FONT_OPEN_SANS_EXTRABOLD_11PX
  &fontOPEN_SANS_EXTRABOLD_11PX_UNICODE ,
#endif //HAVE_BAGL_FONT_OPEN_SANS_EXTRABOLD_11PX

// Nano S
#ifdef HAVE_BAGL_FONT_OPEN_SANS_LIGHT_16PX
  &fontOPEN_SANS_LIGHT_16PX_UNICODE ,
#endif

// Nano S
#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_11PX
  &fontOPEN_SANS_REGULAR_11PX_UNICODE ,
#endif //HAVE_BAGL_FONT_OPEN_SANS_REGULAR_11PX
