
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2021 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

const unsigned char bitmapOPEN_SANS_REGULAR_11PX[] = {
//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0020[   5] = { /* code 0020 */
  0x00,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0021[   5] = { /* code 0021 */
  0x90,  0x24,  0x09,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0022[   6] = { /* code 0022 */
  0x60,  0x06,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0023[  11] = { /* code 0023 */
  0x00,  0x10,  0xC9,  0x4F,  0xA1,  0xFC,  0x24,  0x02,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0024[   9] = { /* code 0024 */
  0x00,  0xE0,  0x29,  0x0A,  0x83,  0x61,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0025[  14] = { /* code 0025 */
  0x00,  0x8C,  0xA8,  0x50,  0xA1,  0xCD,  0x16,  0x2A,
  0x54,  0xC4,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0026[  12] = { /* code 0026 */
  0x00,  0x1C,  0x12,  0x12,  0x0C,  0x4A,  0x52,  0x22,
  0x5E,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0027[   3] = { /* code 0027 */
  0x28,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0028[   5] = { /* code 0028 */
  0x90,  0x94,  0x24,  0x92,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0029[   5] = { /* code 0029 */
  0x90,  0x44,  0x92,  0x92,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_002A[   9] = { /* code 002A */
  0x00,  0x41,  0xFC,  0x8C,  0x04,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_002B[   9] = { /* code 002B */
  0x00,  0x00,  0x00,  0xC8,  0x8F,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_002C[   5] = { /* code 002C */
  0x00,  0x00,  0x00,  0x52,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_002D[   6] = { /* code 002D */
  0x00,  0x00,  0x00,  0x06,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_002E[   5] = { /* code 002E */
  0x00,  0x00,  0x00,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_002F[   6] = { /* code 002F */
  0x80,  0x44,  0x24,  0x22,  0x01,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0030[   9] = { /* code 0030 */
  0x00,  0x23,  0x49,  0x92,  0x24,  0x49,  0x0C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0031[   9] = { /* code 0031 */
  0x00,  0xA3,  0x20,  0x08,  0x82,  0x20,  0x08,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0032[   9] = { /* code 0032 */
  0x80,  0x03,  0x41,  0x10,  0x42,  0x08,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0033[   9] = { /* code 0033 */
  0x80,  0x03,  0x41,  0x0C,  0x04,  0x41,  0x0E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0034[  12] = { /* code 0034 */
  0x00,  0x20,  0x30,  0x28,  0x24,  0x24,  0x7E,  0x20,
  0x20,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0035[   9] = { /* code 0035 */
  0x80,  0x27,  0x08,  0x1E,  0x04,  0x41,  0x0E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0036[   9] = { /* code 0036 */
  0x00,  0x27,  0x08,  0x9E,  0x24,  0x49,  0x0C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0037[   9] = { /* code 0037 */
  0x80,  0x07,  0x41,  0x08,  0x42,  0x10,  0x04,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0038[   9] = { /* code 0038 */
  0x00,  0x23,  0x49,  0x8C,  0x24,  0x49,  0x0C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0039[   9] = { /* code 0039 */
  0x00,  0x23,  0x49,  0x92,  0x07,  0x41,  0x0E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_003A[   5] = { /* code 003A */
  0x00,  0x04,  0x00,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_003B[   5] = { /* code 003B */
  0x00,  0x04,  0x00,  0x52,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_003C[   9] = { /* code 003C */
  0x00,  0x00,  0x21,  0x86,  0x81,  0x40,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_003D[   9] = { /* code 003D */
  0x00,  0x00,  0x00,  0x1E,  0xE0,  0x01,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_003E[   9] = { /* code 003E */
  0x00,  0x20,  0x10,  0x18,  0x46,  0x08,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_003F[   8] = { /* code 003F */
  0xC0,  0x41,  0x88,  0x08,  0x01,  0x04,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0040[  15] = { /* code 0040 */
  0x00,  0xE0,  0x43,  0x90,  0x5C,  0x4A,  0x29,  0xA5,
  0x94,  0x7E,  0x02,  0xF0,  0x01,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0041[  11] = { /* code 0041 */
  0x00,  0x04,  0x85,  0x42,  0x11,  0xF9,  0x44,  0x41,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0042[  11] = { /* code 0042 */
  0x00,  0x9F,  0x48,  0xE4,  0x11,  0x89,  0x44,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0043[  11] = { /* code 0043 */
  0x00,  0x9E,  0x41,  0x20,  0x10,  0x08,  0x0C,  0x3C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0044[  12] = { /* code 0044 */
  0x00,  0x3E,  0x42,  0x42,  0x42,  0x42,  0x42,  0x42,
  0x3E,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0045[   9] = { /* code 0045 */
  0x80,  0x27,  0x08,  0x9E,  0x20,  0x08,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0046[   9] = { /* code 0046 */
  0x80,  0x2F,  0x08,  0x82,  0x2F,  0x08,  0x02,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0047[  12] = { /* code 0047 */
  0x00,  0x7C,  0x02,  0x02,  0x02,  0x62,  0x42,  0x42,
  0x7C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0048[  12] = { /* code 0048 */
  0x00,  0x42,  0x42,  0x42,  0x7E,  0x42,  0x42,  0x42,
  0x42,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0049[   5] = { /* code 0049 */
  0x90,  0x24,  0x49,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_004A[   6] = { /* code 004A */
  0x40,  0x44,  0x44,  0x44,  0x44,  0x03
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_004B[  11] = { /* code 004B */
  0x00,  0x91,  0x44,  0x61,  0x50,  0x48,  0x44,  0x42,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_004C[   9] = { /* code 004C */
  0x80,  0x20,  0x08,  0x82,  0x20,  0x08,  0x3E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_004D[  15] = { /* code 004D */
  0x00,  0x18,  0x66,  0x98,  0x61,  0x4A,  0x29,  0x25,
  0x93,  0x4C,  0x32,  0x01,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_004E[  12] = { /* code 004E */
  0x00,  0x42,  0x46,  0x4A,  0x4A,  0x52,  0x52,  0x62,
  0x42,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_004F[  14] = { /* code 004F */
  0x00,  0xF8,  0x08,  0x12,  0x24,  0x48,  0x90,  0x20,
  0x41,  0x7C,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0050[  11] = { /* code 0050 */
  0x00,  0x8F,  0x48,  0x24,  0xF2,  0x08,  0x04,  0x02,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0051[  14] = { /* code 0051 */
  0x00,  0xF8,  0x08,  0x12,  0x24,  0x48,  0x90,  0x20,
  0x41,  0x7C,  0x40,  0x00,  0x01,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0052[  11] = { /* code 0052 */
  0x00,  0x8F,  0x48,  0x24,  0xF2,  0x48,  0x44,  0x22,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0053[   9] = { /* code 0053 */
  0x00,  0x27,  0x08,  0x06,  0x06,  0x41,  0x0E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0054[  11] = { /* code 0054 */
  0x00,  0x1F,  0x02,  0x81,  0x40,  0x20,  0x10,  0x08,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0055[  12] = { /* code 0055 */
  0x00,  0x42,  0x42,  0x42,  0x42,  0x42,  0x42,  0x42,
  0x3C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0056[  11] = { /* code 0056 */
  0x80,  0xA0,  0x48,  0x24,  0xA2,  0x50,  0x28,  0x08,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0057[  15] = { /* code 0057 */
  0x00,  0xC4,  0x28,  0x93,  0x4C,  0x4A,  0x29,  0xA5,
  0x14,  0x21,  0x84,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0058[   9] = { /* code 0058 */
  0x40,  0x28,  0x31,  0x0C,  0x23,  0x49,  0x21,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0059[   9] = { /* code 0059 */
  0x40,  0x28,  0x49,  0x0C,  0x82,  0x20,  0x08,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_005A[   9] = { /* code 005A */
  0x80,  0x07,  0x21,  0x08,  0x21,  0x08,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_005B[   6] = { /* code 005B */
  0xE0,  0x22,  0x22,  0x22,  0x22,  0x0E
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_005C[   6] = { /* code 005C */
  0x10,  0x22,  0x42,  0x44,  0x08,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_005D[   6] = { /* code 005D */
  0x70,  0x44,  0x44,  0x44,  0x44,  0x07
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_005E[   9] = { /* code 005E */
  0x00,  0xC3,  0x48,  0x52,  0x08,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_005F[   8] = { /* code 005F */
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x7C,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0060[   9] = { /* code 0060 */
  0x04,  0x02,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0061[   9] = { /* code 0061 */
  0x00,  0x00,  0x78,  0x90,  0x27,  0x49,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0062[  11] = { /* code 0062 */
  0x00,  0x81,  0xC0,  0x23,  0x12,  0x89,  0x44,  0x1E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0063[   8] = { /* code 0063 */
  0x00,  0x00,  0x2E,  0x84,  0x10,  0x1C,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0064[  11] = { /* code 0064 */
  0x00,  0x10,  0x88,  0x27,  0x12,  0x89,  0x44,  0x3C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0065[   9] = { /* code 0065 */
  0x00,  0x00,  0x70,  0x92,  0x27,  0x08,  0x1C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0066[   8] = { /* code 0066 */
  0x80,  0x89,  0x27,  0x84,  0x10,  0x02,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0067[   9] = { /* code 0067 */
  0x00,  0x00,  0xF8,  0x92,  0xE4,  0x08,  0x5E,  0x18,
  0x7A
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0068[  11] = { /* code 0068 */
  0x00,  0x81,  0xC0,  0x23,  0x12,  0x89,  0x44,  0x22,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0069[   5] = { /* code 0069 */
  0x10,  0x24,  0x49,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_006A[   6] = { /* code 006A */
  0x40,  0x40,  0x44,  0x44,  0x44,  0x74
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_006B[   9] = { /* code 006B */
  0x80,  0x20,  0x48,  0x8A,  0xA1,  0x48,  0x12,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_006C[   5] = { /* code 006C */
  0x90,  0x24,  0x49,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_006D[  15] = { /* code 006D */
  0x00,  0x00,  0x00,  0x80,  0x77,  0x22,  0x89,  0x24,
  0x92,  0x48,  0x22,  0x01,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_006E[  11] = { /* code 006E */
  0x00,  0x00,  0xC0,  0x23,  0x12,  0x89,  0x44,  0x22,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_006F[  11] = { /* code 006F */
  0x00,  0x00,  0x80,  0x23,  0x12,  0x89,  0x44,  0x1C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0070[  11] = { /* code 0070 */
  0x00,  0x00,  0xC0,  0x23,  0x12,  0x89,  0x44,  0x1E,
  0x81,  0x40,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0071[  11] = { /* code 0071 */
  0x00,  0x00,  0x80,  0x27,  0x12,  0x89,  0x44,  0x3C,
  0x10,  0x08,  0x04
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0072[   6] = { /* code 0072 */
  0x00,  0xE0,  0x22,  0x22,  0x02,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0073[   8] = { /* code 0073 */
  0x00,  0x00,  0x27,  0x0C,  0x82,  0x0E,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0074[   6] = { /* code 0074 */
  0x00,  0xF2,  0x22,  0x22,  0x0E,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0075[  11] = { /* code 0075 */
  0x00,  0x00,  0x40,  0x24,  0x12,  0x89,  0x44,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0076[   9] = { /* code 0076 */
  0x00,  0x00,  0x84,  0x92,  0x24,  0x31,  0x0C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0077[  14] = { /* code 0077 */
  0x00,  0x00,  0x00,  0x88,  0xA8,  0x4A,  0x95,  0x2A,
  0x22,  0x44,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0078[   9] = { /* code 0078 */
  0x00,  0x00,  0x48,  0x12,  0xC3,  0x48,  0x12,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_0079[   9] = { /* code 0079 */
  0x00,  0x00,  0x84,  0x92,  0x24,  0x31,  0x0C,  0x41,
  0x0C
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_007A[   8] = { /* code 007A */
  0x00,  0x80,  0x8F,  0x08,  0x11,  0x1F,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_007B[   6] = { /* code 007B */
  0xC0,  0x44,  0x24,  0x42,  0x44,  0x0C
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_007C[   9] = { /* code 007C */
  0x00,  0x82,  0x20,  0x08,  0x82,  0x20,  0x08,  0x82,
  0x20
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_007D[   6] = { /* code 007D */
  0x30,  0x22,  0x42,  0x24,  0x22,  0x03
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_007E[   9] = { /* code 007E */
  0x00,  0x00,  0x00,  0x06,  0x06,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_REGULAR_11PX_007F[  11] = { /* code 007F */
  0x00,  0x9F,  0x48,  0x24,  0x12,  0x89,  0x44,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

};

const bagl_font_character_t charactersOPEN_SANS_REGULAR_11PX[96] = {
   {   3,   5, 0 }, /* code 0020 */
   {   3,   5, 5 }, /* code 0021 */
   {   4,   6, 10 }, /* code 0022 */
   {   7,  11, 16 }, /* code 0023 */
   {   6,   9, 27 }, /* code 0024 */
   {   9,  14, 36 }, /* code 0025 */
   {   8,  12, 50 }, /* code 0026 */
   {   2,   3, 62 }, /* code 0027 */
   {   3,   5, 65 }, /* code 0028 */
   {   3,   5, 70 }, /* code 0029 */
   {   6,   9, 75 }, /* code 002A */
   {   6,   9, 84 }, /* code 002B */
   {   3,   5, 93 }, /* code 002C */
   {   4,   6, 98 }, /* code 002D */
   {   3,   5, 104 }, /* code 002E */
   {   4,   6, 109 }, /* code 002F */
   {   6,   9, 115 }, /* code 0030 */
   {   6,   9, 124 }, /* code 0031 */
   {   6,   9, 133 }, /* code 0032 */
   {   6,   9, 142 }, /* code 0033 */
   {   8,  12, 151 }, /* code 0034 */
   {   6,   9, 163 }, /* code 0035 */
   {   6,   9, 172 }, /* code 0036 */
   {   6,   9, 181 }, /* code 0037 */
   {   6,   9, 190 }, /* code 0038 */
   {   6,   9, 199 }, /* code 0039 */
   {   3,   5, 208 }, /* code 003A */
   {   3,   5, 213 }, /* code 003B */
   {   6,   9, 218 }, /* code 003C */
   {   6,   9, 227 }, /* code 003D */
   {   6,   9, 236 }, /* code 003E */
   {   5,   8, 245 }, /* code 003F */
   {  10,  15, 253 }, /* code 0040 */
   {   7,  11, 268 }, /* code 0041 */
   {   7,  11, 279 }, /* code 0042 */
   {   7,  11, 290 }, /* code 0043 */
   {   8,  12, 301 }, /* code 0044 */
   {   6,   9, 313 }, /* code 0045 */
   {   6,   9, 322 }, /* code 0046 */
   {   8,  12, 331 }, /* code 0047 */
   {   8,  12, 343 }, /* code 0048 */
   {   3,   5, 355 }, /* code 0049 */
   {   4,   6, 360 }, /* code 004A */
   {   7,  11, 366 }, /* code 004B */
   {   6,   9, 377 }, /* code 004C */
   {  10,  15, 386 }, /* code 004D */
   {   8,  12, 401 }, /* code 004E */
   {   9,  14, 413 }, /* code 004F */
   {   7,  11, 427 }, /* code 0050 */
   {   9,  14, 438 }, /* code 0051 */
   {   7,  11, 452 }, /* code 0052 */
   {   6,   9, 463 }, /* code 0053 */
   {   7,  11, 472 }, /* code 0054 */
   {   8,  12, 483 }, /* code 0055 */
   {   7,  11, 495 }, /* code 0056 */
   {  10,  15, 506 }, /* code 0057 */
   {   6,   9, 521 }, /* code 0058 */
   {   6,   9, 530 }, /* code 0059 */
   {   6,   9, 539 }, /* code 005A */
   {   4,   6, 548 }, /* code 005B */
   {   4,   6, 554 }, /* code 005C */
   {   4,   6, 560 }, /* code 005D */
   {   6,   9, 566 }, /* code 005E */
   {   5,   8, 575 }, /* code 005F */
   {   6,   9, 583 }, /* code 0060 */
   {   6,   9, 592 }, /* code 0061 */
   {   7,  11, 601 }, /* code 0062 */
   {   5,   8, 612 }, /* code 0063 */
   {   7,  11, 620 }, /* code 0064 */
   {   6,   9, 631 }, /* code 0065 */
   {   5,   8, 640 }, /* code 0066 */
   {   6,   9, 648 }, /* code 0067 */
   {   7,  11, 657 }, /* code 0068 */
   {   3,   5, 668 }, /* code 0069 */
   {   4,   6, 673 }, /* code 006A */
   {   6,   9, 679 }, /* code 006B */
   {   3,   5, 688 }, /* code 006C */
   {  10,  15, 693 }, /* code 006D */
   {   7,  11, 708 }, /* code 006E */
   {   7,  11, 719 }, /* code 006F */
   {   7,  11, 730 }, /* code 0070 */
   {   7,  11, 741 }, /* code 0071 */
   {   4,   6, 752 }, /* code 0072 */
   {   5,   8, 758 }, /* code 0073 */
   {   4,   6, 766 }, /* code 0074 */
   {   7,  11, 772 }, /* code 0075 */
   {   6,   9, 783 }, /* code 0076 */
   {   9,  14, 792 }, /* code 0077 */
   {   6,   9, 806 }, /* code 0078 */
   {   6,   9, 815 }, /* code 0079 */
   {   5,   8, 824 }, /* code 007A */
   {   4,   6, 832 }, /* code 007B */
   {   6,   9, 838 }, /* code 007C */
   {   4,   6, 847 }, /* code 007D */
   {   6,   9, 853 }, /* code 007E */
   {   7,  11, 862 }  /* code 007F */
};

const bagl_font_t fontOPEN_SANS_REGULAR_11PX = {
   BAGL_FONT_OPEN_SANS_REGULAR_11px,
   1,
   12 , /* font height in pixels   */
   9  , /* font ascent (baseline) in pixels  */
   0, /* kerning */
   0x0020, /* first character */
   0x007F, /* last character  */
   charactersOPEN_SANS_REGULAR_11PX 
  ,bitmapOPEN_SANS_REGULAR_11PX
};
