
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2021 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

#include "bagl_font_lucida_console_8.inc"

// Nano S
#include "bagl_font_open_sans_extrabold_11px.inc"
#include "bagl_font_open_sans_light_16px.inc"
#include "bagl_font_open_sans_regular_11px.inc"

// Blue
#include "bagl_font_open_sans_light_16_22px.inc"

#include "bagl_font_open_sans_semibold_10_13px.inc"

#include "bagl_font_open_sans_semibold_11_16px.inc"

#include "bagl_font_open_sans_semibold_8_11px.inc"

#include "bagl_font_open_sans_regular_10_13px.inc"

#include "bagl_font_open_sans_regular_11_14px.inc"

#include "bagl_font_open_sans_regular_13_18px.inc"

#include "bagl_font_open_sans_regular_22_30px.inc"

#include "bagl_font_open_sans_regular_8_11px.inc"

#include "bagl_font_open_sans_semibold_13_18px.inc"

#include "bagl_font_symbols.inc"

