
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2021 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX[] = {
//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0020[   5] = { /* code 0020 */
  0x00,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0021[   5] = { /* code 0021 */
  0xB0,  0x6D,  0xC3,  0x06,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0022[   9] = { /* code 0022 */
  0x80,  0x2D,  0x49,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0023[  11] = { /* code 0023 */
  0x00,  0x12,  0xC9,  0x4F,  0xF9,  0x4B,  0x24,  0x12,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0024[   9] = { /* code 0024 */
  0x88,  0xB7,  0x2C,  0x0E,  0x87,  0xA6,  0x1F,  0x02,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0025[  15] = { /* code 0025 */
  0x00,  0x38,  0xB1,  0xC6,  0x0A,  0xFB,  0xF9,  0x8D,
  0x35,  0xD6,  0xC8,  0x01,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0026[  14] = { /* code 0026 */
  0x00,  0x78,  0xD8,  0xB0,  0xC1,  0xC1,  0xDB,  0x3D,
  0x7B,  0xBE,  0x01,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0027[   5] = { /* code 0027 */
  0xB0,  0x04,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0028[   6] = { /* code 0028 */
  0x40,  0x66,  0x33,  0x33,  0x66,  0x04
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0029[   6] = { /* code 0029 */
  0x20,  0x66,  0xCC,  0xCC,  0x66,  0x02
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_002A[   9] = { /* code 002A */
  0x00,  0xD3,  0xFE,  0x9E,  0x07,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_002B[   9] = { /* code 002B */
  0x00,  0xC0,  0x30,  0x3F,  0xC3,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_002C[   5] = { /* code 002C */
  0x00,  0x00,  0xC0,  0x1A,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_002D[   6] = { /* code 002D */
  0x00,  0x00,  0xF0,  0x0F,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_002E[   5] = { /* code 002E */
  0x00,  0x00,  0xC0,  0x06,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_002F[   8] = { /* code 002F */
  0x00,  0x23,  0xC6,  0x8C,  0x11,  0x03,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0030[  12] = { /* code 0030 */
  0x00,  0x3C,  0x66,  0x66,  0x66,  0x66,  0x66,  0x66,
  0x3C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0031[   9] = { /* code 0031 */
  0x00,  0xC6,  0x79,  0x18,  0x86,  0x61,  0x18,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0032[  11] = { /* code 0032 */
  0x00,  0x8E,  0x0D,  0x06,  0xC3,  0x70,  0x18,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0033[  11] = { /* code 0033 */
  0x00,  0x0F,  0x0C,  0xC6,  0x81,  0xC1,  0x60,  0x1E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0034[  12] = { /* code 0034 */
  0x00,  0x30,  0x38,  0x38,  0x34,  0x34,  0x7E,  0x30,
  0x30,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0035[   9] = { /* code 0035 */
  0x80,  0x67,  0x18,  0x1E,  0x86,  0x61,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0036[  12] = { /* code 0036 */
  0x00,  0x38,  0x0C,  0x04,  0x3E,  0x66,  0x66,  0x66,
  0x3C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0037[  11] = { /* code 0037 */
  0x00,  0x1F,  0x0C,  0x06,  0xC3,  0x60,  0x30,  0x0C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0038[  12] = { /* code 0038 */
  0x00,  0x3C,  0x66,  0x66,  0x3C,  0x66,  0x66,  0x66,
  0x3C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0039[  12] = { /* code 0039 */
  0x00,  0x3C,  0x66,  0x66,  0x66,  0x7C,  0x60,  0x30,
  0x1C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_003A[   5] = { /* code 003A */
  0x00,  0x6C,  0xC0,  0x06,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_003B[   5] = { /* code 003B */
  0x00,  0x6C,  0xC0,  0x1A,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_003C[   8] = { /* code 003C */
  0x00,  0x60,  0x66,  0x86,  0x61,  0x18,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_003D[   9] = { /* code 003D */
  0x00,  0x00,  0x00,  0x3F,  0xF0,  0x03,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_003E[   8] = { /* code 003E */
  0x00,  0x0C,  0xC3,  0x30,  0x33,  0x03,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_003F[   9] = { /* code 003F */
  0xC0,  0x83,  0x61,  0x8E,  0x01,  0x18,  0x06,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0040[  15] = { /* code 0040 */
  0x00,  0xE0,  0xC3,  0x98,  0xDD,  0x5B,  0x2F,  0xBD,
  0xF6,  0x7E,  0x06,  0xE0,  0x07,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0041[  12] = { /* code 0041 */
  0x00,  0x18,  0x3C,  0x3C,  0x7E,  0x66,  0x7E,  0xE7,
  0xC3,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0042[  11] = { /* code 0042 */
  0x00,  0x9F,  0xCD,  0xE6,  0xB1,  0xD9,  0x6C,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0043[  11] = { /* code 0043 */
  0x00,  0x9E,  0xC1,  0x60,  0x30,  0x18,  0x0C,  0x3C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0044[  12] = { /* code 0044 */
  0x00,  0x3E,  0x66,  0x66,  0x66,  0x66,  0x66,  0x66,
  0x3E,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0045[   9] = { /* code 0045 */
  0x80,  0x67,  0x18,  0x9E,  0x61,  0x18,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0046[   9] = { /* code 0046 */
  0x80,  0x6F,  0x18,  0x9E,  0x61,  0x18,  0x06,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0047[  12] = { /* code 0047 */
  0x00,  0x7C,  0x06,  0x06,  0x76,  0x66,  0x66,  0x66,
  0x7C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0048[  12] = { /* code 0048 */
  0x00,  0x66,  0x66,  0x66,  0x7E,  0x66,  0x66,  0x66,
  0x66,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0049[   6] = { /* code 0049 */
  0x60,  0x66,  0x66,  0x66,  0x06,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_004A[   8] = { /* code 004A */
  0x80,  0x31,  0xC6,  0x18,  0x63,  0x8C,  0xB1,  0x03
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_004B[  12] = { /* code 004B */
  0x00,  0xE6,  0x66,  0x36,  0x1E,  0x3E,  0x36,  0x66,
  0xE6,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_004C[   9] = { /* code 004C */
  0x80,  0x61,  0x18,  0x86,  0x61,  0x18,  0x3E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_004D[  17] = { /* code 004D */
  0x00,  0x70,  0x9C,  0xE3,  0xBC,  0xE7,  0x3D,  0xEF,
  0x59,  0xCD,  0x6E,  0x76,  0x03,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_004E[  14] = { /* code 004E */
  0x00,  0x9C,  0x39,  0xF3,  0xE6,  0xCD,  0x9E,  0x3D,
  0x73,  0xE6,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_004F[  14] = { /* code 004F */
  0x00,  0xF8,  0x18,  0x33,  0x66,  0xCC,  0x98,  0x31,
  0x63,  0x7C,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0050[  11] = { /* code 0050 */
  0x00,  0x9F,  0xCD,  0x66,  0xF3,  0x19,  0x0C,  0x06,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0051[  14] = { /* code 0051 */
  0x00,  0xF8,  0x18,  0x33,  0x66,  0xCC,  0x98,  0x31,
  0x63,  0x7C,  0xC0,  0x00,  0x03,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0052[  12] = { /* code 0052 */
  0x00,  0x1E,  0x36,  0x36,  0x36,  0x1E,  0x36,  0x36,
  0x66,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0053[   9] = { /* code 0053 */
  0x00,  0x6F,  0x18,  0x0E,  0x87,  0xE7,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0054[   9] = { /* code 0054 */
  0xC0,  0xCF,  0x30,  0x0C,  0xC3,  0x30,  0x0C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0055[  12] = { /* code 0055 */
  0x00,  0x66,  0x66,  0x66,  0x66,  0x66,  0x66,  0x66,
  0x3C,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0056[   9] = { /* code 0056 */
  0xC0,  0x3C,  0xCF,  0xB3,  0xE7,  0x79,  0x0C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0057[  17] = { /* code 0057 */
  0x00,  0x98,  0xB3,  0xDD,  0xEC,  0x66,  0x35,  0xAB,
  0x71,  0x87,  0x3B,  0xD8,  0x00,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0058[  12] = { /* code 0058 */
  0x00,  0xC3,  0x66,  0x3C,  0x3C,  0x3C,  0x3C,  0x66,
  0xC3,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0059[  11] = { /* code 0059 */
  0x80,  0xB1,  0xCD,  0xC6,  0xC1,  0x60,  0x30,  0x18,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_005A[  11] = { /* code 005A */
  0x80,  0x3F,  0x0C,  0x87,  0x61,  0x38,  0x0C,  0x7F,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_005B[   8] = { /* code 005B */
  0xC0,  0x1B,  0x63,  0x8C,  0x31,  0xC6,  0x78,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_005C[   8] = { /* code 005C */
  0x60,  0x08,  0x63,  0x18,  0x43,  0x18,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_005D[   8] = { /* code 005D */
  0xE0,  0x31,  0xC6,  0x18,  0x63,  0x8C,  0x3D,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_005E[  11] = { /* code 005E */
  0x00,  0x06,  0xC3,  0x23,  0x99,  0x01,  0x00,  0x00,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_005F[   9] = { /* code 005F */
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0xF0,
  0x03
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0060[  11] = { /* code 0060 */
  0x0C,  0x0C,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0061[  11] = { /* code 0061 */
  0x00,  0x00,  0xC0,  0x03,  0xF3,  0xCD,  0x66,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0062[  11] = { /* code 0062 */
  0x00,  0x83,  0xC1,  0x67,  0xB3,  0xDB,  0x6D,  0x3E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0063[   9] = { /* code 0063 */
  0x00,  0x00,  0xF0,  0xC6,  0x71,  0x18,  0x3C,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0064[  11] = { /* code 0064 */
  0x00,  0x18,  0x8C,  0x67,  0xBB,  0xDD,  0x6C,  0x3C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0065[  11] = { /* code 0065 */
  0x00,  0x00,  0x80,  0x67,  0xFE,  0x1F,  0x0C,  0x3C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0066[   9] = { /* code 0066 */
  0x00,  0x67,  0x7C,  0x86,  0x61,  0x18,  0x06,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0067[  11] = { /* code 0067 */
  0x00,  0x00,  0xC0,  0x6F,  0xB3,  0x79,  0x0C,  0xBE,
  0xF1,  0xD8,  0x07
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0068[  11] = { /* code 0068 */
  0x00,  0x83,  0xC1,  0x67,  0xB3,  0xD9,  0x6C,  0x36,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0069[   6] = { /* code 0069 */
  0x60,  0x60,  0x66,  0x66,  0x06,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_006A[   8] = { /* code 006A */
  0x80,  0x01,  0xC6,  0x18,  0x63,  0x8C,  0x31,  0x03
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_006B[  11] = { /* code 006B */
  0x00,  0x83,  0xC1,  0xE6,  0xF3,  0x78,  0x6C,  0x76,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_006C[   6] = { /* code 006C */
  0x60,  0x66,  0x66,  0x66,  0x06,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_006D[  15] = { /* code 006D */
  0x00,  0x00,  0x00,  0x80,  0x76,  0xB6,  0xD9,  0x66,
  0x9B,  0x6D,  0xB6,  0x01,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_006E[  11] = { /* code 006E */
  0x00,  0x00,  0x40,  0x67,  0xB3,  0xD9,  0x6C,  0x36,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_006F[  11] = { /* code 006F */
  0x00,  0x00,  0x80,  0x63,  0xBB,  0xDF,  0x6D,  0x1C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0070[  11] = { /* code 0070 */
  0x00,  0x00,  0xC0,  0x67,  0xB3,  0xDB,  0x6D,  0x3E,
  0x83,  0xC1,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0071[  11] = { /* code 0071 */
  0x00,  0x00,  0xC0,  0x67,  0xBB,  0xDD,  0x6C,  0x3E,
  0x18,  0x0C,  0x06
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0072[   8] = { /* code 0072 */
  0x00,  0x00,  0xED,  0x8D,  0x31,  0x06,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0073[   9] = { /* code 0073 */
  0x00,  0x00,  0x78,  0x86,  0xC7,  0xC3,  0x1E,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0074[   8] = { /* code 0074 */
  0x00,  0x98,  0x6F,  0x8C,  0x31,  0x1C,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0075[  11] = { /* code 0075 */
  0x00,  0x00,  0xC0,  0x66,  0xB3,  0xD9,  0x6C,  0x2E,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0076[  11] = { /* code 0076 */
  0x00,  0x00,  0x60,  0x6C,  0xB3,  0xD9,  0x38,  0x1C,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0077[  15] = { /* code 0077 */
  0x00,  0x00,  0x00,  0xC0,  0xCC,  0xB6,  0xF9,  0xE7,
  0x1F,  0x33,  0xCC,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0078[  11] = { /* code 0078 */
  0x00,  0x00,  0xE0,  0x6E,  0xE3,  0x70,  0x6C,  0x77,
  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_0079[  11] = { /* code 0079 */
  0x00,  0x00,  0x60,  0x6C,  0xB3,  0xD1,  0x38,  0x1C,
  0x06,  0xC3,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_007A[   9] = { /* code 007A */
  0x00,  0x00,  0xFC,  0x18,  0xC3,  0x18,  0x3F,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_007B[   8] = { /* code 007B */
  0x80,  0x33,  0xC6,  0xCE,  0x61,  0x8C,  0x71,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_007C[   9] = { /* code 007C */
  0x00,  0xC3,  0x30,  0x0C,  0xC3,  0x30,  0x0C,  0xC3,
  0x30
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_007D[   8] = { /* code 007D */
  0xE0,  0x18,  0x63,  0x38,  0x37,  0xC6,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_007E[   9] = { /* code 007E */
  0x00,  0x00,  0x00,  0x6F,  0x0F,  0x00,  0x00,  0x00,
  0x00
  ,
//};

//const unsigned char bitmapOPEN_SANS_EXTRABOLD_11PX_007F[   9] = { /* code 007F */
  0x80,  0x27,  0x49,  0x92,  0x24,  0x49,  0x1E,  0x00,
  0x00
  ,
//};

};

const bagl_font_character_t charactersOPEN_SANS_EXTRABOLD_11PX[96] = {
   {   3,   5, 0 }, /* code 0020 */
   {   3,   5, 5 }, /* code 0021 */
   {   6,   9, 10 }, /* code 0022 */
   {   7,  11, 19 }, /* code 0023 */
   {   6,   9, 30 }, /* code 0024 */
   {  10,  15, 39 }, /* code 0025 */
   {   9,  14, 54 }, /* code 0026 */
   {   3,   5, 68 }, /* code 0027 */
   {   4,   6, 73 }, /* code 0028 */
   {   4,   6, 79 }, /* code 0029 */
   {   6,   9, 85 }, /* code 002A */
   {   6,   9, 94 }, /* code 002B */
   {   3,   5, 103 }, /* code 002C */
   {   4,   6, 108 }, /* code 002D */
   {   3,   5, 114 }, /* code 002E */
   {   5,   8, 119 }, /* code 002F */
   {   8,  12, 127 }, /* code 0030 */
   {   6,   9, 139 }, /* code 0031 */
   {   7,  11, 148 }, /* code 0032 */
   {   7,  11, 159 }, /* code 0033 */
   {   8,  12, 170 }, /* code 0034 */
   {   6,   9, 182 }, /* code 0035 */
   {   8,  12, 191 }, /* code 0036 */
   {   7,  11, 203 }, /* code 0037 */
   {   8,  12, 214 }, /* code 0038 */
   {   8,  12, 226 }, /* code 0039 */
   {   3,   5, 238 }, /* code 003A */
   {   3,   5, 243 }, /* code 003B */
   {   5,   8, 248 }, /* code 003C */
   {   6,   9, 256 }, /* code 003D */
   {   5,   8, 265 }, /* code 003E */
   {   6,   9, 273 }, /* code 003F */
   {  10,  15, 282 }, /* code 0040 */
   {   8,  12, 297 }, /* code 0041 */
   {   7,  11, 309 }, /* code 0042 */
   {   7,  11, 320 }, /* code 0043 */
   {   8,  12, 331 }, /* code 0044 */
   {   6,   9, 343 }, /* code 0045 */
   {   6,   9, 352 }, /* code 0046 */
   {   8,  12, 361 }, /* code 0047 */
   {   8,  12, 373 }, /* code 0048 */
   {   4,   6, 385 }, /* code 0049 */
   {   5,   8, 391 }, /* code 004A */
   {   8,  12, 399 }, /* code 004B */
   {   6,   9, 411 }, /* code 004C */
   {  11,  17, 420 }, /* code 004D */
   {   9,  14, 437 }, /* code 004E */
   {   9,  14, 451 }, /* code 004F */
   {   7,  11, 465 }, /* code 0050 */
   {   9,  14, 476 }, /* code 0051 */
   {   8,  12, 490 }, /* code 0052 */
   {   6,   9, 502 }, /* code 0053 */
   {   6,   9, 511 }, /* code 0054 */
   {   8,  12, 520 }, /* code 0055 */
   {   6,   9, 532 }, /* code 0056 */
   {  11,  17, 541 }, /* code 0057 */
   {   8,  12, 558 }, /* code 0058 */
   {   7,  11, 570 }, /* code 0059 */
   {   7,  11, 581 }, /* code 005A */
   {   5,   8, 592 }, /* code 005B */
   {   5,   8, 600 }, /* code 005C */
   {   5,   8, 608 }, /* code 005D */
   {   7,  11, 616 }, /* code 005E */
   {   6,   9, 627 }, /* code 005F */
   {   7,  11, 636 }, /* code 0060 */
   {   7,  11, 647 }, /* code 0061 */
   {   7,  11, 658 }, /* code 0062 */
   {   6,   9, 669 }, /* code 0063 */
   {   7,  11, 678 }, /* code 0064 */
   {   7,  11, 689 }, /* code 0065 */
   {   6,   9, 700 }, /* code 0066 */
   {   7,  11, 709 }, /* code 0067 */
   {   7,  11, 720 }, /* code 0068 */
   {   4,   6, 731 }, /* code 0069 */
   {   5,   8, 737 }, /* code 006A */
   {   7,  11, 745 }, /* code 006B */
   {   4,   6, 756 }, /* code 006C */
   {  10,  15, 762 }, /* code 006D */
   {   7,  11, 777 }, /* code 006E */
   {   7,  11, 788 }, /* code 006F */
   {   7,  11, 799 }, /* code 0070 */
   {   7,  11, 810 }, /* code 0071 */
   {   5,   8, 821 }, /* code 0072 */
   {   6,   9, 829 }, /* code 0073 */
   {   5,   8, 838 }, /* code 0074 */
   {   7,  11, 846 }, /* code 0075 */
   {   7,  11, 857 }, /* code 0076 */
   {  10,  15, 868 }, /* code 0077 */
   {   7,  11, 883 }, /* code 0078 */
   {   7,  11, 894 }, /* code 0079 */
   {   6,   9, 905 }, /* code 007A */
   {   5,   8, 914 }, /* code 007B */
   {   6,   9, 922 }, /* code 007C */
   {   5,   8, 931 }, /* code 007D */
   {   6,   9, 939 }, /* code 007E */
   {   6,   9, 948 }  /* code 007F */
};

const bagl_font_t fontOPEN_SANS_EXTRABOLD_11PX = {
   BAGL_FONT_OPEN_SANS_EXTRABOLD_11px,
   1,
   12 , /* font height in pixels   */
   9  , /* font ascent (baseline) in pixels  */
   0, /* kerning */
   0x0020, /* first character */
   0x007F, /* last character  */
   charactersOPEN_SANS_EXTRABOLD_11PX 
  ,bitmapOPEN_SANS_EXTRABOLD_11PX
};
