
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2021 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

#ifdef HAVE_BAGL_FONT_LUCIDA_CONSOLE_8PX
  &fontLUCIDA_CONSOLE_8,
#endif // HAVE_BAGL_FONT_LUCIDA_CONSOLE_8

#ifdef HAVE_BAGL_FONT_OPEN_SANS_LIGHT_16_22PX
  &fontOPEN_SANS_LIGHT_16_22PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_8_11PX
  &fontOPEN_SANS_REGULAR_8_11PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_10_13PX
  &fontOPEN_SANS_REGULAR_10_13PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_11_14PX
  &fontOPEN_SANS_REGULAR_11_14PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_13_18PX
  &fontOPEN_SANS_REGULAR_13_18PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_22_30PX
  &fontOPEN_SANS_REGULAR_22_30PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_SEMIBOLD_8_11PX
  &fontOPEN_SANS_SEMIBOLD_8_11PX,
#endif

// Nano S
#ifdef HAVE_BAGL_FONT_OPEN_SANS_EXTRABOLD_11PX
  &fontOPEN_SANS_EXTRABOLD_11PX ,
#endif

// Nano S
#ifdef HAVE_BAGL_FONT_OPEN_SANS_LIGHT_16PX
  &fontOPEN_SANS_LIGHT_16PX ,
#endif

// Nano S
#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_11PX
  &fontOPEN_SANS_REGULAR_11PX ,
#endif

/////////

#ifdef HAVE_BAGL_FONT_OPEN_SANS_SEMIBOLD_10_13PX
  &fontOPEN_SANS_SEMIBOLD_10_13PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_SEMIBOLD_11_16PX
  &fontOPEN_SANS_SEMIBOLD_11_16PX,
#endif

#ifdef HAVE_BAGL_FONT_OPEN_SANS_SEMIBOLD_13_18PX
  &fontOPEN_SANS_SEMIBOLD_13_18PX,
#endif

#ifdef HAVE_BAGL_FONT_SYMBOLS_0
  &fontSYMBOLS_0,
#endif

#ifdef HAVE_BAGL_FONT_SYMBOLS_1
  &fontSYMBOLS_1,
#endif
