
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2021 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

/*******************************************************************************
 * Font name: Lucida Console                                                   *
 * Font width: 5 (monospaced font)                                             *
 * Font height: 8                                                              *
 * Encode: Unicode                                                             *
 * Data length: 8 bits                                                         *
 * Invert bits: No                                                             *
 * Data format: Big Endian, Row based, Row preferred, Packed                   *
 *******************************************************************************/

const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H[] = {
//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0020[   5] = { /* code 0020 */
  0x00,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0021[   5] = { /* code 0021 */
  0x84,  0x10,  0x02,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0022[   5] = { /* code 0022 */
  0x4A,  0x01,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0023[   5] = { /* code 0023 */
  0x80,  0x7E,  0xF5,  0x0B,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0024[   5] = { /* code 0024 */
  0xC4,  0x19,  0xC2,  0x1C,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0025[   5] = { /* code 0025 */
  0xB2,  0x3A,  0x57,  0x13,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0026[   5] = { /* code 0026 */
  0x44,  0x99,  0x9A,  0x2C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0027[   5] = { /* code 0027 */
  0x84,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0028[   5] = { /* code 0028 */
  0x98,  0x08,  0x21,  0x08,  0x06
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0029[   5] = { /* code 0029 */
  0x83,  0x20,  0x84,  0xC8,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_002A[   5] = { /* code 002A */
  0x44,  0x11,  0x05,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_002B[   5] = { /* code 002B */
  0x00,  0x00,  0xE2,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_002C[   5] = { /* code 002C */
  0x00,  0x00,  0x00,  0x08,  0x11
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_002D[   5] = { /* code 002D */
  0x00,  0x00,  0x07,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_002E[   5] = { /* code 002E */
  0x00,  0x00,  0x00,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_002F[   5] = { /* code 002F */
  0x10,  0x21,  0x42,  0x84,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0030[   5] = { /* code 0030 */
  0x4C,  0x4A,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0031[   5] = { /* code 0031 */
  0xC4,  0x10,  0x42,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0032[   5] = { /* code 0032 */
  0x06,  0x21,  0x22,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0033[   5] = { /* code 0033 */
  0x06,  0x19,  0x84,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0034[   5] = { /* code 0034 */
  0x88,  0x29,  0x8F,  0x10,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0035[   5] = { /* code 0035 */
  0x4E,  0x18,  0x84,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0036[   5] = { /* code 0036 */
  0x4C,  0x38,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0037[   5] = { /* code 0037 */
  0x1E,  0x22,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0038[   5] = { /* code 0038 */
  0x4C,  0x32,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0039[   5] = { /* code 0039 */
  0x4C,  0x4A,  0x0E,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_003A[   5] = { /* code 003A */
  0x00,  0x10,  0x00,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_003B[   5] = { /* code 003B */
  0x00,  0x10,  0x00,  0x08,  0x11
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_003C[   5] = { /* code 003C */
  0x00,  0x22,  0x83,  0x20,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_003D[   5] = { /* code 003D */
  0x00,  0x78,  0xE0,  0x01,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_003E[   5] = { /* code 003E */
  0x40,  0x10,  0x4C,  0x04,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_003F[   5] = { /* code 003F */
  0x0E,  0x22,  0x02,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0040[   5] = { /* code 0040 */
  0x4C,  0xE6,  0xDA,  0x83,  0x07
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0041[   5] = { /* code 0041 */
  0x80,  0x28,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0042[   5] = { /* code 0042 */
  0xC0,  0x29,  0xA3,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0043[   5] = { /* code 0043 */
  0x80,  0x0B,  0x21,  0x38,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0044[   5] = { /* code 0044 */
  0xC0,  0x49,  0x29,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0045[   5] = { /* code 0045 */
  0xC0,  0x09,  0x27,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0046[   5] = { /* code 0046 */
  0xC0,  0x09,  0x27,  0x04,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0047[   5] = { /* code 0047 */
  0x80,  0x0B,  0x2D,  0x39,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0048[   5] = { /* code 0048 */
  0x40,  0x4A,  0x2F,  0x25,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0049[   5] = { /* code 0049 */
  0xC0,  0x11,  0x42,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_004A[   5] = { /* code 004A */
  0xC0,  0x21,  0x84,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_004B[   5] = { /* code 004B */
  0x40,  0x2A,  0xA3,  0x24,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_004C[   5] = { /* code 004C */
  0x40,  0x08,  0x21,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_004D[   5] = { /* code 004D */
  0x20,  0xEE,  0x5A,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_004E[   5] = { /* code 004E */
  0x40,  0x5A,  0x2D,  0x25,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_004F[   5] = { /* code 004F */
  0xC0,  0xC5,  0x18,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0050[   5] = { /* code 0050 */
  0xC0,  0x49,  0x27,  0x04,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0051[   5] = { /* code 0051 */
  0xC0,  0xC5,  0x18,  0x1D,  0x82
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0052[   5] = { /* code 0052 */
  0xC0,  0x28,  0xA3,  0x24,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0053[   5] = { /* code 0053 */
  0x80,  0x09,  0x82,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0054[   5] = { /* code 0054 */
  0xE0,  0x13,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0055[   5] = { /* code 0055 */
  0x40,  0x4A,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0056[   5] = { /* code 0056 */
  0x40,  0x4A,  0xC9,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0057[   5] = { /* code 0057 */
  0x20,  0xD6,  0xAA,  0x14,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0058[   5] = { /* code 0058 */
  0x20,  0x2A,  0xA2,  0x22,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0059[   5] = { /* code 0059 */
  0x20,  0x2A,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_005A[   5] = { /* code 005A */
  0xC0,  0x43,  0x26,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_005B[   5] = { /* code 005B */
  0x8C,  0x10,  0x42,  0x08,  0x03
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_005C[   5] = { /* code 005C */
  0x41,  0x08,  0x42,  0x10,  0x02
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_005D[   5] = { /* code 005D */
  0x86,  0x10,  0x42,  0x88,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_005E[   5] = { /* code 005E */
  0x44,  0xA9,  0x18,  0x01,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_005F[   5] = { /* code 005F */
  0x00,  0x00,  0x00,  0xC0,  0x07
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0060[   5] = { /* code 0060 */
  0x82,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0061[   5] = { /* code 0061 */
  0x00,  0x18,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0062[   5] = { /* code 0062 */
  0x42,  0x38,  0x29,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0063[   5] = { /* code 0063 */
  0x00,  0x30,  0x21,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0064[   5] = { /* code 0064 */
  0x08,  0xB9,  0x94,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0065[   5] = { /* code 0065 */
  0x00,  0x10,  0x27,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0066[   5] = { /* code 0066 */
  0x98,  0x78,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0067[   5] = { /* code 0067 */
  0x00,  0x70,  0xE9,  0xA1,  0x03
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0068[   5] = { /* code 0068 */
  0x42,  0x28,  0x2B,  0x25,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0069[   5] = { /* code 0069 */
  0x04,  0x18,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_006A[   5] = { /* code 006A */
  0x08,  0x38,  0x84,  0x90,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_006B[   5] = { /* code 006B */
  0x42,  0x28,  0xA3,  0x24,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_006C[   5] = { /* code 006C */
  0x86,  0x10,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_006D[   5] = { /* code 006D */
  0x00,  0xD4,  0x5F,  0x2B,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_006E[   5] = { /* code 006E */
  0x00,  0x28,  0x2B,  0x25,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_006F[   5] = { /* code 006F */
  0x00,  0x30,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0070[   5] = { /* code 0070 */
  0x00,  0x38,  0x29,  0x9D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0071[   5] = { /* code 0071 */
  0x00,  0xB8,  0x94,  0x1C,  0x02
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0072[   5] = { /* code 0072 */
  0x00,  0x28,  0x23,  0x04,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0073[   5] = { /* code 0073 */
  0x00,  0x30,  0x83,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0074[   5] = { /* code 0074 */
  0x80,  0x78,  0x42,  0x10,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0075[   5] = { /* code 0075 */
  0x00,  0x48,  0xA9,  0x29,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0076[   5] = { /* code 0076 */
  0x00,  0x48,  0xC9,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0077[   5] = { /* code 0077 */
  0x00,  0xD4,  0xEA,  0x14,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0078[   5] = { /* code 0078 */
  0x00,  0x48,  0xC6,  0x24,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_0079[   5] = { /* code 0079 */
  0x00,  0x48,  0xC9,  0xD8,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_007A[   5] = { /* code 007A */
  0x00,  0x38,  0x26,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_007B[   5] = { /* code 007B */
  0x88,  0x10,  0x41,  0x08,  0x02
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_007C[   5] = { /* code 007C */
  0x84,  0x10,  0x42,  0x08,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_007D[   5] = { /* code 007D */
  0x82,  0x10,  0x44,  0x88,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_007E[   5] = { /* code 007E */
  0x00,  0x00,  0x9B,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_007F[   5] = { /* code 007F */
  0xC0,  0x29,  0xA5,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A0[   5] = { /* code 00A0 */
  0x00,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A1[   5] = { /* code 00A1 */
  0x00,  0x10,  0x40,  0x08,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A2[   5] = { /* code 00A2 */
  0x80,  0x38,  0xE1,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A3[   5] = { /* code 00A3 */
  0x80,  0x08,  0x33,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A4[   5] = { /* code 00A4 */
  0x20,  0x3A,  0xE5,  0x22,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A5[   5] = { /* code 00A5 */
  0x20,  0x2A,  0xE2,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A6[   5] = { /* code 00A6 */
  0x84,  0x10,  0x00,  0x08,  0x21
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A7[   5] = { /* code 00A7 */
  0x4C,  0x10,  0x45,  0x90,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A8[   5] = { /* code 00A8 */
  0x0A,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00A9[   5] = { /* code 00A9 */
  0x2E,  0xF6,  0xDA,  0xA3,  0x03
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00AA[   5] = { /* code 00AA */
  0x06,  0x39,  0xE5,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00AB[   5] = { /* code 00AB */
  0x80,  0xAA,  0xA2,  0x28,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00AC[   5] = { /* code 00AC */
  0x00,  0x00,  0x87,  0x10,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00AD[   5] = { /* code 00AD */
  0x00,  0x00,  0x07,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00AE[   5] = { /* code 00AE */
  0xAE,  0xF7,  0xDA,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00AF[   5] = { /* code 00AF */
  0x1F,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B0[   5] = { /* code 00B0 */
  0x4C,  0x4A,  0x06,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B1[   5] = { /* code 00B1 */
  0x00,  0x10,  0x47,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B2[   5] = { /* code 00B2 */
  0x06,  0x11,  0xE1,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B3[   5] = { /* code 00B3 */
  0x06,  0x19,  0x64,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B4[   5] = { /* code 00B4 */
  0x88,  0x00,  0x00,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B5[   5] = { /* code 00B5 */
  0x00,  0x48,  0xA9,  0xAD,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B6[   5] = { /* code 00B6 */
  0x6E,  0x2D,  0xA5,  0x94,  0x02
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B7[   5] = { /* code 00B7 */
  0x00,  0x00,  0x02,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B8[   5] = { /* code 00B8 */
  0x00,  0x00,  0x00,  0x00,  0x11
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00B9[   5] = { /* code 00B9 */
  0x86,  0x10,  0xE2,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00BA[   5] = { /* code 00BA */
  0x44,  0x29,  0x45,  0x00,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00BB[   5] = { /* code 00BB */
  0xA0,  0x28,  0xAA,  0x0A,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00BC[   5] = { /* code 00BC */
  0x53,  0x29,  0xAA,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00BD[   5] = { /* code 00BD */
  0x53,  0x79,  0xAA,  0x32,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00BE[   5] = { /* code 00BE */
  0x73,  0xA9,  0xAB,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00BF[   5] = { /* code 00BF */
  0x80,  0x00,  0x42,  0x90,  0x01
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C0[   5] = { /* code 00C0 */
  0x82,  0x28,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C1[   5] = { /* code 00C1 */
  0x88,  0x28,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C2[   5] = { /* code 00C2 */
  0x4C,  0x12,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C3[   5] = { /* code 00C3 */
  0x36,  0x11,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C4[   5] = { /* code 00C4 */
  0x8A,  0x28,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C5[   5] = { /* code 00C5 */
  0x44,  0x11,  0xF5,  0x23,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C6[   5] = { /* code 00C6 */
  0x80,  0x2B,  0xFD,  0x32,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C7[   5] = { /* code 00C7 */
  0x80,  0x0B,  0x21,  0x38,  0x22
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C8[   5] = { /* code 00C8 */
  0xC1,  0x09,  0x27,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00C9[   5] = { /* code 00C9 */
  0xD0,  0x09,  0x27,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00CA[   5] = { /* code 00CA */
  0xCE,  0x09,  0x27,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00CB[   5] = { /* code 00CB */
  0xD1,  0x09,  0x27,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00CC[   5] = { /* code 00CC */
  0xC1,  0x11,  0x42,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00CD[   5] = { /* code 00CD */
  0xD0,  0x11,  0x42,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00CE[   5] = { /* code 00CE */
  0xCE,  0x11,  0x42,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00CF[   5] = { /* code 00CF */
  0xD1,  0x11,  0x42,  0x1C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D0[   5] = { /* code 00D0 */
  0xC0,  0xC9,  0x2B,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D1[   5] = { /* code 00D1 */
  0x5F,  0x5A,  0x2D,  0x25,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D2[   5] = { /* code 00D2 */
  0xC1,  0xC5,  0x18,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D3[   5] = { /* code 00D3 */
  0xD0,  0xC5,  0x18,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D4[   5] = { /* code 00D4 */
  0xCE,  0xC5,  0x18,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D5[   5] = { /* code 00D5 */
  0xCF,  0xC5,  0x18,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D6[   5] = { /* code 00D6 */
  0xD1,  0xC5,  0x18,  0x1D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D7[   5] = { /* code 00D7 */
  0x00,  0x48,  0xC6,  0x24,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D8[   5] = { /* code 00D8 */
  0xD0,  0xE5,  0x3A,  0x5D,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00D9[   5] = { /* code 00D9 */
  0x41,  0x4A,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00DA[   5] = { /* code 00DA */
  0x30,  0xA5,  0x94,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00DB[   5] = { /* code 00DB */
  0x5E,  0x4A,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00DC[   5] = { /* code 00DC */
  0x49,  0x4A,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00DD[   5] = { /* code 00DD */
  0xA8,  0x2A,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00DE[   5] = { /* code 00DE */
  0x40,  0x38,  0xE9,  0x04,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00DF[   5] = { /* code 00DF */
  0x44,  0x29,  0x25,  0x15,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E0[   5] = { /* code 00E0 */
  0x41,  0x18,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E1[   5] = { /* code 00E1 */
  0x10,  0x19,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E2[   5] = { /* code 00E2 */
  0x4C,  0x1A,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E3[   5] = { /* code 00E3 */
  0x36,  0x19,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E4[   5] = { /* code 00E4 */
  0x0A,  0x18,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E5[   5] = { /* code 00E5 */
  0x44,  0x19,  0xE4,  0x3C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E6[   5] = { /* code 00E6 */
  0x00,  0x2C,  0x7E,  0x32,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E7[   5] = { /* code 00E7 */
  0x00,  0x30,  0x21,  0x18,  0x22
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E8[   5] = { /* code 00E8 */
  0x41,  0x10,  0x27,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00E9[   5] = { /* code 00E9 */
  0x10,  0x11,  0x27,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00EA[   5] = { /* code 00EA */
  0x4C,  0x12,  0x27,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00EB[   5] = { /* code 00EB */
  0x0A,  0x10,  0x27,  0x18,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00EC[   5] = { /* code 00EC */
  0x41,  0x18,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00ED[   5] = { /* code 00ED */
  0x10,  0x19,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00EE[   5] = { /* code 00EE */
  0x4C,  0x1A,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00EF[   5] = { /* code 00EF */
  0x0A,  0x18,  0x42,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F0[   5] = { /* code 00F0 */
  0x8F,  0xB8,  0x94,  0x0C,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F1[   5] = { /* code 00F1 */
  0x1E,  0x28,  0x2B,  0x25,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F2[   5] = { /* code 00F2 */
  0x41,  0x30,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F3[   5] = { /* code 00F3 */
  0x10,  0x31,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F4[   5] = { /* code 00F4 */
  0x26,  0x31,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F5[   5] = { /* code 00F5 */
  0x36,  0x31,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F6[   5] = { /* code 00F6 */
  0x12,  0x30,  0x29,  0x19,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F7[   5] = { /* code 00F7 */
  0x80,  0x00,  0x07,  0x08,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F8[   5] = { /* code 00F8 */
  0x00,  0x32,  0x6D,  0x99,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00F9[   5] = { /* code 00F9 */
  0x82,  0x48,  0xA9,  0x29,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00FA[   5] = { /* code 00FA */
  0x10,  0x49,  0xA9,  0x29,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00FB[   5] = { /* code 00FB */
  0x26,  0x49,  0xA9,  0x29,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00FC[   5] = { /* code 00FC */
  0x12,  0x48,  0xA9,  0x29,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00FD[   5] = { /* code 00FD */
  0x10,  0x49,  0xC9,  0xD8,  0x00
  ,
//};

//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00FE[   5] = { /* code 00FE */
  0x42,  0x38,  0x29,  0x9D,  0x00
  ,
//};


//const unsigned char bitmapLUCIDA_CONSOLE_6PT_8H_00FF[   5] = { /* code 00FF */
  0x12,  0x48,  0xC9,  0xD8,  0x01
  ,
//};



};

const bagl_font_character_t charactersLUCIDA_CONSOLE_6PT_8H[664] = {
   {   5,   5, 0 }, /* code 0020 */
   {   5,   5, 5 }, /* code 0021 */
   {   5,   5, 10 }, /* code 0022 */
   {   5,   5, 15 }, /* code 0023 */
   {   5,   5, 20 }, /* code 0024 */
   {   5,   5, 25 }, /* code 0025 */
   {   5,   5, 30 }, /* code 0026 */
   {   5,   5, 35 }, /* code 0027 */
   {   5,   5, 40 }, /* code 0028 */
   {   5,   5, 45 }, /* code 0029 */
   {   5,   5, 50 }, /* code 002A */
   {   5,   5, 55 }, /* code 002B */
   {   5,   5, 60 }, /* code 002C */
   {   5,   5, 65 }, /* code 002D */
   {   5,   5, 70 }, /* code 002E */
   {   5,   5, 75 }, /* code 002F */
   {   5,   5, 80 }, /* code 0030 */
   {   5,   5, 85 }, /* code 0031 */
   {   5,   5, 90 }, /* code 0032 */
   {   5,   5, 95 }, /* code 0033 */
   {   5,   5, 100 }, /* code 0034 */
   {   5,   5, 105 }, /* code 0035 */
   {   5,   5, 110 }, /* code 0036 */
   {   5,   5, 115 }, /* code 0037 */
   {   5,   5, 120 }, /* code 0038 */
   {   5,   5, 125 }, /* code 0039 */
   {   5,   5, 130 }, /* code 003A */
   {   5,   5, 135 }, /* code 003B */
   {   5,   5, 140 }, /* code 003C */
   {   5,   5, 145 }, /* code 003D */
   {   5,   5, 150 }, /* code 003E */
   {   5,   5, 155 }, /* code 003F */
   {   5,   5, 160 }, /* code 0040 */
   {   5,   5, 165 }, /* code 0041 */
   {   5,   5, 170 }, /* code 0042 */
   {   5,   5, 175 }, /* code 0043 */
   {   5,   5, 180 }, /* code 0044 */
   {   5,   5, 185 }, /* code 0045 */
   {   5,   5, 190 }, /* code 0046 */
   {   5,   5, 195 }, /* code 0047 */
   {   5,   5, 200 }, /* code 0048 */
   {   5,   5, 205 }, /* code 0049 */
   {   5,   5, 210 }, /* code 004A */
   {   5,   5, 215 }, /* code 004B */
   {   5,   5, 220 }, /* code 004C */
   {   5,   5, 225 }, /* code 004D */
   {   5,   5, 230 }, /* code 004E */
   {   5,   5, 235 }, /* code 004F */
   {   5,   5, 240 }, /* code 0050 */
   {   5,   5, 245 }, /* code 0051 */
   {   5,   5, 250 }, /* code 0052 */
   {   5,   5, 255 }, /* code 0053 */
   {   5,   5, 260 }, /* code 0054 */
   {   5,   5, 265 }, /* code 0055 */
   {   5,   5, 270 }, /* code 0056 */
   {   5,   5, 275 }, /* code 0057 */
   {   5,   5, 280 }, /* code 0058 */
   {   5,   5, 285 }, /* code 0059 */
   {   5,   5, 290 }, /* code 005A */
   {   5,   5, 295 }, /* code 005B */
   {   5,   5, 300 }, /* code 005C */
   {   5,   5, 305 }, /* code 005D */
   {   5,   5, 310 }, /* code 005E */
   {   5,   5, 315 }, /* code 005F */
   {   5,   5, 320 }, /* code 0060 */
   {   5,   5, 325 }, /* code 0061 */
   {   5,   5, 330 }, /* code 0062 */
   {   5,   5, 335 }, /* code 0063 */
   {   5,   5, 340 }, /* code 0064 */
   {   5,   5, 345 }, /* code 0065 */
   {   5,   5, 350 }, /* code 0066 */
   {   5,   5, 355 }, /* code 0067 */
   {   5,   5, 360 }, /* code 0068 */
   {   5,   5, 365 }, /* code 0069 */
   {   5,   5, 370 }, /* code 006A */
   {   5,   5, 375 }, /* code 006B */
   {   5,   5, 380 }, /* code 006C */
   {   5,   5, 385 }, /* code 006D */
   {   5,   5, 390 }, /* code 006E */
   {   5,   5, 395 }, /* code 006F */
   {   5,   5, 400 }, /* code 0070 */
   {   5,   5, 405 }, /* code 0071 */
   {   5,   5, 410 }, /* code 0072 */
   {   5,   5, 415 }, /* code 0073 */
   {   5,   5, 420 }, /* code 0074 */
   {   5,   5, 425 }, /* code 0075 */
   {   5,   5, 430 }, /* code 0076 */
   {   5,   5, 435 }, /* code 0077 */
   {   5,   5, 440 }, /* code 0078 */
   {   5,   5, 445 }, /* code 0079 */
   {   5,   5, 450 }, /* code 007A */
   {   5,   5, 455 }, /* code 007B */
   {   5,   5, 460 }, /* code 007C */
   {   5,   5, 465 }, /* code 007D */
   {   5,   5, 470 }, /* code 007E */
   {   5,   5, 475 }, /* code 007F */
   {   5,   5, 480 }, /* code 00A0 */
   {   5,   5, 485 }, /* code 00A1 */
   {   5,   5, 490 }, /* code 00A2 */
   {   5,   5, 495 }, /* code 00A3 */
   {   5,   5, 500 }, /* code 00A4 */
   {   5,   5, 505 }, /* code 00A5 */
   {   5,   5, 510 }, /* code 00A6 */
   {   5,   5, 515 }, /* code 00A7 */
   {   5,   5, 520 }, /* code 00A8 */
   {   5,   5, 525 }, /* code 00A9 */
   {   5,   5, 530 }, /* code 00AA */
   {   5,   5, 535 }, /* code 00AB */
   {   5,   5, 540 }, /* code 00AC */
   {   5,   5, 545 }, /* code 00AD */
   {   5,   5, 550 }, /* code 00AE */
   {   5,   5, 555 }, /* code 00AF */
   {   5,   5, 560 }, /* code 00B0 */
   {   5,   5, 565 }, /* code 00B1 */
   {   5,   5, 570 }, /* code 00B2 */
   {   5,   5, 575 }, /* code 00B3 */
   {   5,   5, 580 }, /* code 00B4 */
   {   5,   5, 585 }, /* code 00B5 */
   {   5,   5, 590 }, /* code 00B6 */
   {   5,   5, 595 }, /* code 00B7 */
   {   5,   5, 600 }, /* code 00B8 */
   {   5,   5, 605 }, /* code 00B9 */
   {   5,   5, 610 }, /* code 00BA */
   {   5,   5, 615 }, /* code 00BB */
   {   5,   5, 620 }, /* code 00BC */
   {   5,   5, 625 }, /* code 00BD */
   {   5,   5, 630 }, /* code 00BE */
   {   5,   5, 635 }, /* code 00BF */
   {   5,   5, 640 }, /* code 00C0 */
   {   5,   5, 645 }, /* code 00C1 */
   {   5,   5, 650 }, /* code 00C2 */
   {   5,   5, 655 }, /* code 00C3 */
   {   5,   5, 660 }, /* code 00C4 */
   {   5,   5, 665 }, /* code 00C5 */
   {   5,   5, 670 }, /* code 00C6 */
   {   5,   5, 675 }, /* code 00C7 */
   {   5,   5, 680 }, /* code 00C8 */
   {   5,   5, 685 }, /* code 00C9 */
   {   5,   5, 690 }, /* code 00CA */
   {   5,   5, 695 }, /* code 00CB */
   {   5,   5, 700 }, /* code 00CC */
   {   5,   5, 705 }, /* code 00CD */
   {   5,   5, 710 }, /* code 00CE */
   {   5,   5, 715 }, /* code 00CF */
   {   5,   5, 720 }, /* code 00D0 */
   {   5,   5, 725 }, /* code 00D1 */
   {   5,   5, 730 }, /* code 00D2 */
   {   5,   5, 735 }, /* code 00D3 */
   {   5,   5, 740 }, /* code 00D4 */
   {   5,   5, 745 }, /* code 00D5 */
   {   5,   5, 750 }, /* code 00D6 */
   {   5,   5, 755 }, /* code 00D7 */
   {   5,   5, 760 }, /* code 00D8 */
   {   5,   5, 765 }, /* code 00D9 */
   {   5,   5, 770 }, /* code 00DA */
   {   5,   5, 775 }, /* code 00DB */
   {   5,   5, 780 }, /* code 00DC */
   {   5,   5, 785 }, /* code 00DD */
   {   5,   5, 790 }, /* code 00DE */
   {   5,   5, 795 }, /* code 00DF */
   {   5,   5, 800 }, /* code 00E0 */
   {   5,   5, 805 }, /* code 00E1 */
   {   5,   5, 810 }, /* code 00E2 */
   {   5,   5, 815 }, /* code 00E3 */
   {   5,   5, 820 }, /* code 00E4 */
   {   5,   5, 825 }, /* code 00E5 */
   {   5,   5, 830 }, /* code 00E6 */
   {   5,   5, 835 }, /* code 00E7 */
   {   5,   5, 840 }, /* code 00E8 */
   {   5,   5, 845 }, /* code 00E9 */
   {   5,   5, 850 }, /* code 00EA */
   {   5,   5, 855 }, /* code 00EB */
   {   5,   5, 860 }, /* code 00EC */
   {   5,   5, 865 }, /* code 00ED */
   {   5,   5, 870 }, /* code 00EE */
   {   5,   5, 875 }, /* code 00EF */
   {   5,   5, 880 }, /* code 00F0 */
   {   5,   5, 885 }, /* code 00F1 */
   {   5,   5, 890 }, /* code 00F2 */
   {   5,   5, 895 }, /* code 00F3 */
   {   5,   5, 900 }, /* code 00F4 */
   {   5,   5, 905 }, /* code 00F5 */
   {   5,   5, 910 }, /* code 00F6 */
   {   5,   5, 915 }, /* code 00F7 */
   {   5,   5, 920 }, /* code 00F8 */
   {   5,   5, 925 }, /* code 00F9 */
   {   5,   5, 930 }, /* code 00FA */
   {   5,   5, 935 }, /* code 00FB */
   {   5,   5, 940 }, /* code 00FC */
   {   5,   5, 945 }, /* code 00FD */
   {   5,   5, 950 }, /* code 00FE */
   {   5,   5, 955 }, /* code 00FF */
};

const bagl_font_t fontLUCIDA_CONSOLE_8 = {
	 BAGL_FONT_LUCIDA_CONSOLE_8PX,
   1,
   8 , /* font height in pixels   */
   16 , /* baseline distance from top */
   0, /* kerning */
   0x0020, /* first character */
   0x00FF, /* last character  */
   charactersLUCIDA_CONSOLE_6PT_8H /* address of first character */
  ,bitmapLUCIDA_CONSOLE_6PT_8H
};
