
#include "bagl_font_lucida_console_8.inc"

// Nano S
#include "bagl_font_open_sans_extrabold_11px.inc"
#include "bagl_font_open_sans_light_16px.inc"
#include "bagl_font_open_sans_regular_11px.inc"

// Blue
#include "bagl_font_open_sans_light_16_22px.inc"

#include "bagl_font_open_sans_semibold_10_13px.inc"

#include "bagl_font_open_sans_semibold_11_16px.inc"

#include "bagl_font_open_sans_semibold_8_11px.inc"

#include "bagl_font_open_sans_regular_10_13px.inc"

#include "bagl_font_open_sans_regular_11_14px.inc"

#include "bagl_font_open_sans_regular_13_18px.inc"

#include "bagl_font_open_sans_regular_22_30px.inc"

#include "bagl_font_open_sans_regular_8_11px.inc"

#include "bagl_font_open_sans_semibold_13_18px.inc"

#include "bagl_font_symbols.inc"

