
/*******************************************************************************
*   Ledger Nano S - Secure firmware
*   (c) 2022 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

#ifdef HAVE_BAGL_FONT_INTER_REGULAR_24PX
  &fontINTER_REGULAR_24PX,
#endif // HAVE_BAGL_FONT_INTER_REGULAR_24PX

#ifdef HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX
  &fontINTER_SEMIBOLD_24PX,
#endif // HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX

#ifdef HAVE_BAGL_FONT_INTER_MEDIUM_32PX
  &fontINTER_MEDIUM_32PX,
#endif // HAVE_BAGL_FONT_INTER_MEDIUM_32PX

#ifdef HAVE_BAGL_FONT_INTER_REGULAR_24PX
  &fontINTER_REGULAR_24PX_1BPP,
#endif // HAVE_BAGL_FONT_INTER_REGULAR_24PX

#ifdef HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX
  &fontINTER_SEMIBOLD_24PX_1BPP,
#endif // HAVE_BAGL_FONT_INTER_SEMIBOLD_24PX

#ifdef HAVE_BAGL_FONT_INTER_MEDIUM_32PX
  &fontINTER_MEDIUM_32PX_1BPP,
#endif // HAVE_BAGL_FONT_INTER_MEDIUM_32PX

#ifdef HAVE_BAGL_FONT_OPEN_SANS_EXTRABOLD_11PX
  &fontOPEN_SANS_EXTRABOLD_11PX_1BPP,
#endif // HAVE_BAGL_FONT_OPEN_SANS_EXTRABOLD_11PX

#ifdef HAVE_BAGL_FONT_OPEN_SANS_LIGHT_16PX
  &fontOPEN_SANS_LIGHT_16PX_1BPP,
#endif // HAVE_BAGL_FONT_OPEN_SANS_LIGHT_16PX

#ifdef HAVE_BAGL_FONT_OPEN_SANS_REGULAR_11PX
  &fontOPEN_SANS_REGULAR_11PX_1BPP,
#endif // HAVE_BAGL_FONT_OPEN_SANS_REGULAR_11PX

#ifdef HAVE_BAGL_FONT_INTER_REGULAR_28PX
  &fontINTER_REGULAR_28PX,
#endif // HAVE_BAGL_FONT_INTER_REGULAR_28PX

#ifdef HAVE_BAGL_FONT_INTER_SEMIBOLD_28PX
  &fontINTER_SEMIBOLD_28PX,
#endif // HAVE_BAGL_FONT_INTER_SEMIBOLD_28PX

#ifdef HAVE_BAGL_FONT_INTER_MEDIUM_36PX
  &fontINTER_MEDIUM_36PX,
#endif // HAVE_BAGL_FONT_INTER_MEDIUM_36PX

#ifdef HAVE_BAGL_FONT_INTER_REGULAR_28PX
  &fontINTER_REGULAR_28PX_1BPP,
#endif // HAVE_BAGL_FONT_INTER_REGULAR_28PX

#ifdef HAVE_BAGL_FONT_INTER_SEMIBOLD_28PX
  &fontINTER_SEMIBOLD_28PX_1BPP,
#endif // HAVE_BAGL_FONT_INTER_SEMIBOLD_28PX

#ifdef HAVE_BAGL_FONT_INTER_MEDIUM_36PX
  &fontINTER_MEDIUM_36PX_1BPP,
#endif // HAVE_BAGL_FONT_INTER_MEDIUM_36PX
